see-main/see/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('see/',include('rate_employees.urls')),
]

see-main/rate_employees/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Employee(models.Model):
    empid = models.IntegerField()
    enothi_id = models.CharField(max_length=40)
    ename = models.CharField(max_length=40)
    eemail = models.EmailField(max_length=40)
    edesignation = models.CharField(max_length=40)
    edept = models.CharField(max_length=40)
    esection = models.CharField(max_length=40)
    edivision = models.CharField(max_length=40, default='null_div')
    edirectorate = models.CharField(max_length=40)
    counter = models.IntegerField(default=10)
    

    def setEname(self,ename):
        self.ename = ename

 
class Evaluation(models.Model):
    evaluateeid = models.IntegerField()
    evaluatorid = models.IntegerField()
    secDeptEv = models.IntegerField(default=None)
    commEv = models.IntegerField(default=None)
    behavEv = models.IntegerField(default=None)
    comid = models.IntegerField(default=None)


class Designation(models.Model):
    desigid = models.IntegerField()
    designame = models.CharField(max_length=40)
    desigshortname = models.CharField(max_length=40)

    
class Award(models.Model):
    awardid = models.AutoField(primary_key=True)
    advisorid= models.IntegerField(default=0)
    award_evaluatorid = models.IntegerField(default=0)
    award_evaluateeid = models.IntegerField(default=0)
    purposeid=models.CharField(max_length=40)
    description= models.CharField(max_length=400)
    remark=models.CharField(max_length=50,default=" ")
    
    Status = models.IntegerField(default=0)
    


class Notification(models.Model):
    recipient = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='notifications')
    sender = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='sent_notifications')
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Notification from {self.sender} to {self.recipient}'    

see-main/templates/employees/award.html
{% extends "employees/home.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evaluation</title>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <!-- Custom Styles -->
    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #e3f2fd;
            color: #333; /* Text color */
        }
        .btn-red {
            background-color: #0044ff; /* Blue background color */
            color: #ffffff; /* White text color */
            border: none; /* Remove default border */
            padding: 10px 15px; /* Add some padding */
            border-radius: 5px; /* Round corners */
            width: 40%; /* Maintain button size */
            transition: none; /* Disable transition effects */
        }
        .btn-red:hover {
            background-color: #1565c0 !important; /* Darker blue on hover */
        }
        .user_card {
            width: 550px;
            margin: auto;
            margin-top: 0 px;
            background: #f8f9fa; /* Light gray background */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        #form-title {
            background-color: #0044ff; /* Blue background for title */
            color: #fff; /* White text color */
            padding: 10px;
            text-align: center;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .form-container {
            margin-top: 20px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-row {
            display: flex;
            align-items: center;
            margin-bottom: 15px;
        }
        .form-row label {
            width: 180px;
            text-align: right;
            margin-right: 10px;
            color: #000; /* Black label text color */
        }
        .form-row textarea,
        .form-row input {
            flex: 1;
            min-width: 200px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
            color: #333; /* Text color for inputs */
            background-color: #fff; /* White background for inputs */
        }
        /* Custom styles for the "Seek Permission from" textarea */
        #seek {
            height: 60px; /* Adjust height as needed */
            resize: none; /* Disable resizing */
            text-align: center; /* Center text */
        }
        /* Styles for the message */
        .message {
            display: inline-block;
            vertical-align: middle;
            margin-left: 10px;
            color: red;
            font-weight: bold;
        }
        /* Custom styles for the search input */
        #searchInput {
            width: 100%;
            padding: 10px;
            font-size: 14px;
            color: #333;
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        /* Custom styles for the employee list */
        #employeeList {
            list-style-type: none;
            padding: 0;
        }
        .list-group-item {
            cursor: pointer;
            padding: 10px;
            margin-bottom: 5px;
            background-color: #f8f9fa;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .list-group-item:hover {
            background-color: #e9ecef;
            color:  #0044ff;
        }
    </style>
</head>
<body>
    <div class="container-fluid h-100">
        <div class="row justify-content-center h-100">
            <div class="col-lg-6">
                <div class="user_card">
                    <h3 id="form-title">Award</h3>
                    <form action="{% url 'award' %}" method="post" class="form-container">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="Name">Select Employee:</label>
                            <input type="text" id="searchInput" class="form-control" placeholder="enothi or name" onkeyup="searchEmployee()" required>
                            <input type="hidden" id="employeeIdInput" name="employee" required>
                            <ul id="employeeList" class="list-group mt-2"></ul>
                        </div>
                        <div class="form-group">
                            <label for="purpose">Purpose:</label>
                            <input type="text" id="purpose" name="purpose" class="form-control" size="30" required>
                        </div>
                        <div class="form-group">
                            <label for="description">Description:</label>
                            <textarea id="description" name="description" class="form-control" rows="4" cols="50" required></textarea>
                        </div>
                        <div class="form-group">
                            <label for="seek">Seek Permission from:</label>
                            <div>
                                [{{ advisor_object.enothi_id }}] - {{ advisor_object.ename }} - ({{ade}}-{{adi}})
                            </div>
                            <textarea id="seek" name="seek" style="display: none;">{{ advisor_object.enothi_id }}</textarea>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-red" value="Submit">
                            {% if messages %}
                            <div class="message">
                                {% for message in messages %}
                                <p>{{ message }}</p>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Your custom script -->
    <script>
        function searchEmployee() {
            const query = document.getElementById('searchInput').value;
            if (query.length < 3) {
                document.getElementById('employeeList').innerHTML = '';
                return;
            }
            fetch(`api/search-award/?q=${query}`)
                .then(response => response.json())
                .then(data => {
                    const employeeList = document.getElementById('employeeList');
                    employeeList.innerHTML = '';
                    data.employees.forEach(emp => {
                        const listItem = document.createElement('li');
                        listItem.className = 'list-group-item';
                        listItem.innerHTML = `[${emp.enothi_id}] ${emp.name}`;
                        listItem.onclick = () => selectEmployee(emp.name, emp.enothi_id);
                        employeeList.appendChild(listItem);
                    });
                })
                .catch(error => console.error('Error searching employee:', error));
        }

        function selectEmployee(name, enothi_id) {
            document.getElementById('searchInput').value = `[${enothi_id}] ${name}`;
            document.getElementById('employeeIdInput').value = enothi_id;
            document.getElementById('employeeList').innerHTML = '';
        }
    </script>
</body>
</html>

{% endblock %}

see-main/templates/employees/awardreport.html
{% extends "employees/home.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Award Report</title>
    <style>
        body {
            background-color: #e3f2fd;
            font-family: 'Arial', sans-serif;
        }
        .container {
            max-width: 90%;
            margin-top: 20px;
        }
        .user_card {
            background: #ffffff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 20px;
        }
        .form-title {
            font-weight: bold;
            color: #343a40;
            text-align: center;
            margin-bottom: 20px;
        }
        .table-container {
            max-height: 700px;
            overflow-y: auto;
            overflow-x: auto;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 8px 10px;
            border: 1px solid #dee2e6;
            text-align: center;
            font-size: 14px;
        }
        th {
            background-color: #343a40;
            color: #ffffff;
        }
        td {
            background-color: #ffffff;
        }
        .status-btn {
            border: none;
            background: none;
            color: blue;
            cursor: pointer;
        }
        .btn-options {
            display: none;
            margin-top: 10px;
        }
        .btn-options button {
            margin: 5px;
        }
        .login_btn {
            width: 50%;
            background: #007bff !important;
            color: #ffffff !important;
            border: none;
            padding: 10px;
            border-radius: 5px;
            transition: background 0.3s;
        }
        .login_btn:hover {
            background: #0056b3 !important;
        }
        @media (max-width: 768px) {
            .table-container {
                width: 100%;
            }
            th, td {
                font-size: 12px;
                padding: 6px 8px;
            }
        }
        .description-column {
            width: 40%;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="user_card">
            <h3 class="form-title">Award Report</h3>
            <div class="table-container">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Advisor</th>
                            <th>Evaluator Name</th>
                            <th>Evaluatee Name</th>
                            <th>Purpose</th>
                            <th class="description-column">Description</th>
                            <th>Remark</th>
                            <th>Status</th>
                           
                            
                        </tr>
                    </thead>
                    <tbody>
                        {% for report in report_data %}
                        <tr id="row-{{ report.award_id }}">
                            <form action="" method="post" novalidate> 
                                {% csrf_token %}
                                <td>{{ report.advisorid }}</td>
                                <td>{{ report.evaluator_name }}</td>
                                <td>{{ report.evaluatee_name }}</td>
                                <td>{{ report.purpose }}</td>
                                <td class="description-column">{{ report.description }}</td>
                                <td>{{ report.remark }}</td>
                                <td>{{ report.status }}</td>
                               
                           
                            </form>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="d-flex justify-content-center">
                    <input class="login_btn" type="submit" name="profile" value="Home">
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>
{% endblock %}

see-main/templates/employees/evaluate.html
{% extends "employees/home.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complete Your Profile</title>
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <!-- Custom Styles -->
    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #e3f2fd;
            color: #333; /* Text color */
        }
        .btn-red {
            background-color: #0044ff; /* Blue background color */
            color: #ffffff; /* White text color */
            border: none; /* Remove default border */
            padding: 10px 15px; /* Match padding with other buttons */
            border-radius: 5px; /* Round corners */
            width: 100%; /* Full-width button to match other buttons */
            transition: none; /* Disable transition effects */
        }
        .btn-red:hover {
            background-color: #1565c0 !important; /* Darker blue on hover */
        }
        .user_card {
            width: 550px;
            margin: auto;
            margin-top: 0;
            background: #f8f9fa; /* Light gray background */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        #form-title {
            background-color: #0044ff; /* Blue background for title */
            color: #fff; /* White text color */
            padding: 10px;
            text-align: center;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .form-container {
            margin-top: 20px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-row {
            display: flex;
            align-items: center;
            margin-bottom: 15px;
        }
        .form-row label {
            width: 180px;
            text-align: right;
            margin-right: 10px;
            color: #000; /* Black label text color */
        }
        .form-row textarea,
        .form-row input {
            flex: 1;
            min-width: 200px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
            color: #333; /* Text color for inputs */
            background-color: #fff; /* White background for inputs */
        }
        #seek {
            height: 60px; /* Adjust height as needed */
            resize: none; /* Disable resizing */
            text-align: center; /* Center text */
        }
        .message {
            display: inline-block;
            vertical-align: middle;
            margin-left: 10px;
            color: red;
            font-weight: bold;
        }
        #searchInput {
            width: 100%;
            padding: 10px;
            font-size: 14px;
            color: #333;
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        #employeeList {
            list-style-type: none;
            padding: 0;
        }
        .list-group-item {
            cursor: pointer;
            padding: 10px;
            margin-bottom: 5px;
            background-color: #f8f9fa;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .list-group-item:hover {
            background-color: #e9ecef;
            color: #0044ff;
        }
    </style>
</head>
<body>
    <div class="container-fluid h-100">
        <div class="row justify-content-center h-100">
            <div class="col-lg-6">
                <div class="user_card">
                    <h3 id="form-title">Evaluate Here</h3>
                    <form action="" method="post" class="form-container" id="evaluationForm">
                        {% csrf_token %}
                        <div class="profile-item">
                            <b>Name:</b> {{evaluateeData.ename}}
                        </div>
                        <div class="profile-item">
                            <b>Designation:</b> {{designation_name}}
                        </div>
                        <div class="profile-item">
                            <b>Division:</b> {{division_name}}
                        </div>
                        <input id="evaluateeid" name="evaluateeid" type="hidden" value="{{evaluateeData.empid}}">

                        <ol>
                            <li>
                                Same Division: <br>
                                <label for="secDept">Observation:</label>
                                <select name="secDept" id="secDept" required>
                                    <option selected disabled>Select Remark..</option>
                                    <option value="1">Excellent</option>
                                    <option value="2">Very Good</option>
                                    <option value="3">Good</option>
                                    <option value="4">Average</option>
                                </select>
                            </li>
                            <li>
                                Committee Work: <br>
                                <label for="record">Record Number:</label>
                                <input type="text" id="record" name="record"><br>
                                <label for="purpose">Committee Purpose:</label>
                                <input type="text" id="purpose" name="purpose"><br>
                                <label for="committee">Observation:</label>
                                <select name="committee" id="committee" required>
                                    <option selected disabled>Select Remark..</option>
                                    <option value="1">Excellent</option>
                                    <option value="2">Very Good</option>
                                    <option value="3">Good</option>
                                    <option value="4">Average</option>
                                </select>
                            </li>
                            <li>
                                Overall Behaviour: <br>
                                <label for="behaviour">Observation:</label>
                                <select name="behaviour" id="behaviour" required>
                                    <option selected disabled>Select Remark..</option>
                                    <option value="1">Excellent</option>
                                    <option value="2">Very Good</option>
                                    <option value="3">Good</option>
                                    <option value="4">Average</option>
                                </select>
                            </li>
                        </ol>

                        <div class="form-group">
                            
                            <input class="btn btn-red" type="submit" name="profile" value="Save">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $('#evaluationForm').submit(function(e) {
                var behaviourValue = $('#behaviour').val();
                if (behaviourValue === null || behaviourValue === "") {
                    alert("Please select an option for Overall Behaviour.");
                    e.preventDefault(); // Prevent form submission
                }
            });
        });
    </script>
</body>
</html>

{% endblock %}

see-main/templates/employees/mark.html
<!DOCTYPE html>
<html>
<body>

<h2>HTML Forms</h2>

<form action="/action_page.php">
  <label for="mbehave">Behaviour:</label>
  <input type="number" id="mbehave" name="mbehave" min="1" max="100"><br><br>
  <label for="mdesk">Desk Work:</label>
  <input type="number" id="mdesk" name="mdesk" min="1" max="100"><br><br>
  <label for="mcom">Committee Work:</label>
  <input type="number" id="mcom" name="mcom" min="1" max="100"><br><br>

  <input type="submit" value="Submit">
</form> 




<p>If you click the "Submit" button, the form-data will be sent to a page called "/action_page.php".</p>

</body>
</html>

see-main/templates/employees/profile3.html
{% extends "employees/home.html" %}

{% block content %}

<!DOCTYPE html>

<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complete Your Profile</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            // Function to filter options based on search input
            $('#search_employee').on('input', function() {
                var searchText = $(this).val().toLowerCase();
                $('#id_employees option').each(function() {
                    var optionText = $(this).text().toLowerCase();
                    var match = optionText.indexOf(searchText) > -1;
                    $(this).toggle(match);
                });
            });

            // AJAX request when selecting an employee
            $('#id_employees').change(function() {
                var selectedName = $(this).val();
                $.ajax({
                    type: 'GET',
                    data: {
                        'employee_name': selectedName
                    },
                    success: function(response) {
                        $('#id_name').val(response.name);
                        $('#id_designation').val(response.designation);
                        $('#id_division').val(response.division);
                        $('#id_empid').val(response.empid);
                    },
                    error: function(xhr, errmsg, err) {
                        console.log(errmsg);
                    }
                });
            });
        });
    </script>

    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #e3f2fd; /* Light teal background */
            color: #333; /* Text color */
        }
        .btn-red {
            background-color: #ff5722 !important; /* Red background */
            color: #ffffff !important; /* White text */
        }
        .btn-red:hover {
            background-color: #e64a19 !important; /* Darker red on hover */
        }
        .user_card {
            width: 550px;
            margin: auto;
            margin-top: 20px;
            background: #ffffff; /* White background for card */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        #form-title {
            background-color: #0044ff; /* Blue background for title */
            color: #ffffff; /* White text color */
            padding: 10px;
            text-align: center;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .form-container {
            margin-top: 20px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-row {
            display: flex;
            align-items: center;
            margin-bottom: 15px;
        }
        .form-row label {
            width: 180px;
            text-align: right;
            margin-right: 10px;
            color: #000; /* Black label text color */
        }
        .form-row textarea,
        .form-row input {
            flex: 1;
            min-width: 200px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
            color: #333; /* Text color for inputs */
            background-color: #fff; /* White background for inputs */
        }
        .login-btn {
            width: 40%;
            background: #0044ff; /* Blue button */
            color: #ffffff;
            border: none;
            padding: 10px 15px;
            margin-top: 10px;
        }
        .login-btn:focus {
            box-shadow: none;
            outline: none;
        }
        /* Custom styles for the "Remark" select */
        #remark {
            text-align: center; /* Center text */
        }
        /* Styles for the message */
        .message {
            display: inline-block;
            vertical-align: middle;
            margin-left: 10px;
            color: red;
            font-weight: bold;
        }
        .profile-item {
            margin-bottom: 10px; /* Optional: Add some margin between items */
        }
        .profile-item b {
            display: inline-block;
            width: 150px; /* Adjust width as needed for alignment */
        }
    </style>

</head>

<body>
    <div class="container-fluid h-100">
        <div class="row justify-content-center h-100">
            <div class="col-lg-6">
                <div class="user_card">
                    <h3 id="form-title">Profile</h3>

                    <form action="" method="post" novalidate> {% csrf_token %}

                        <div class="profile-item">
                            <b>Name </b>{{ myProfileData.ename }}<br>
                        </div>
                        <div class="profile-item">
                            <b>Employee ID </b>{{ myProfileData.empid }}<br>
                        </div>
                        <div class="profile-item">
                            <b>Email </b>{{ myProfileData.eemail }}<br>
                        </div>
                        <div class="profile-item">
                            <b>Designation </b>{{ designation_name }}<br>
                        </div>
                        <div class="profile-item">
                            <b>Division </b>{{ division_name }}<br>
                        </div>

                        <div class="profile-item">
                            <b>Evaluation Counter </b>{{evaluation_count}} / {{employee_count}}<br>
                        </div>
                        <div class="profile-item">
                            <b>Award Counter </b>{{counter}}/10<br>
                        </div>

                        <br>
                        <br>
                        <i>
                            If the above information needs to be updated, please contact the IT department!
                        </i>

                        <div class="d-flex justify-content-center">
                            <input class="btn btn-dark login-btn btn-blue" type="submit" name="profile" value="Home">
                        </div>
                    </form>

                </div>

            </div>

        </div>

    </div>

</body>

<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
    //We start indexing at one because CSRF_token is considered and input field 
    */

    // Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = 'Search by Name..';
    form_fields[2].placeholder = '';
    form_fields[3].placeholder = '';

    for (var field in form_fields) {
        form_fields[field].className += ' form-control'
    }
</script>

</html>

{% endblock %}